version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: ~/tmp
    steps:
      - checkout
      - run: npm install
      
 test:
  steps:
    - run: npm test
  post:
    - bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
            
            